@token=8A:
@tenant=Cust12345
@env=sod
@ticket=7T:
@client_secret=1234567890



GET https://{{env}}.superoffice.com/{{tenant}}/api/v1/archive/dynamic?$select=kb_entry.id,kb_entry.title HTTP/1.1
Accept: application/json
Authorization: Bearer {{token}}

###

GET https://{{env}}.superoffice.com/{{tenant}}/api/v1/archive/dynamic?$select=kb_entry.id,kb_entry.title HTTP/1.1
Accept: application/json
Authorization: Bearer {{token}}

###

POST https://{{env}}.superoffice.com/{{tenant}}/api/v1/Agents/Archive/GetAvailableColumns HTTP/1.1
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "ProviderName": "TicketMessage",
  "Context": ""
}

###


GET https://{{env}}.superoffice.com/{{tenant}}/api/v1/archive/dynamic?$select=ej_message.ticket_id,ej_message.badge HTTP/1.1
Accept: application/json
Authorization: Bearer {{token}}

###

GET https://{{env}}.superoffice.com/{{tenant}}/api/v1/archive/dynamic?$select=UDListDefinition.UDListDefinition_id,UDListDefinition.name,UDListDefinition.listTableId,UDListDefinition.listTableId.(sequence->TableNumber).TableName HTTP/1.1
Accept: application/json
Authorization: Bearer {{token}}

###

GET https://{{env}}.superoffice.com/{{tenant}}/api/v1/archive/dynamic?$select=sequence.id,sequence.TableName,sequence.TableNumber HTTP/1.1
Accept: application/json
Authorization: Bearer {{token}}

###

GET https://{{env}}.superoffice.com/{{tenant}}/api/v1/archive/dynamic?$select=contact.name,contact.department,contact.(contactinterest->contact_id).cinterest_idx&$filter=contact.contact_id eq 13418 HTTP/1.1
Accept: application/json
Authorization: Bearer {{token}}

###

POST https://{{env}}.superoffice.com/{{tenant}}/api/v1/Agents/Archive/GetArchiveListByColumns HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
  "ProviderName": "Ticket",
  "Columns": [
    "CountAll(ticketId)"
  ],
  "SortOrder": [
    {
      "Name": "ticketId",
      "Direction": "ASC"
    }
  ],
  "Restriction": [
    {
      "Name": "ticketId",
      "Operator": ">",
      "Values": [
        "0"
      ],
      "IsActive": true
    }
  ],
  "Entities": [
    "ticket"
  ],
  "Page": 0,
  "PageSize": 1000000
}

###

POST https://{{env}}.superoffice.com/{{tenant}}/api/v1/Agents/Find/FindFromRestrictionsColumns HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
  "ProviderName": "Dynamic",
  "DesiredColumns": [
    "getAllRows",
    "Count(kb_entry.id)",
    "kb_entry.id",
    "kb_entry.title",
    "kb_entry.x_parent",
    "kb_entry.question",
    "kb_entry.answer",
    "kb_entry.keywords",
    "kb_entry.x_registered",
    "kb_entry.(y_so_faq_product->id).x_product"
  ],
  "Restrictions": [
    {
      "Name": "kb_entry.workflow_phase",
      "Operator": "=",
      "Values": [
        "-2"
      ],
      "IsActive": true
    },
    {
      "Name": "kb_entry.access_level",
      "Operator": "in",
      "Values": [
        "3",
        "4"
      ],
      "IsActive": true
    }
  ],
  "Page": 0,
  "PageSize": 100
}



###

POST https://{{env}}.superoffice.com/{{tenant}}/api/v1/Agents/Archive/GetArchiveListByColumns?$select=contactId,name HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
  "ProviderName": "FindContact",
  "Columns": [
    "contactId",
    "name"
  ],
  "SortOrder": [
    {
      "Name": "contactId",
      "Direction": "ASC"
    }
  ],
  "Restriction": [
    {
      "Name": "contactId",
      "Operator": "in",
      "Values": [
        "5",
        "6",
        "7",
        "8",
        "9",
        "10",
        "11",
        "12",
        "13"
      ],
      "IsActive": true
    }
  ],
  "Entities": [
    "contact"
  ],
  "Page": 0,
  "PageSize": 1000000
}

###

POST https://{{env}}.superoffice.com/{{tenant}}/api/v1/Agents/Archive/GetArchiveListByColumns?$select=contactId,name HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
  "ProviderName": "FindContact",
  "Columns": [
    "contactId",
    "name"
  ],
  "SortOrder": [
    {
      "Name": "contactId",
      "Direction": "ASC"
    }
  ],
  "Restriction": [
    {
      "Name": "name",
      "Operator": "in",
      "Values": [
        "Google Inc.",
        "Testing Orgnr",
        "Razors Edge"
      ],
      "IsActive": true
    }
  ],
  "Entities": [
    "contact"
  ],
  "Page": 0,
  "PageSize": 1000000
}


###

GET https://{{env}}.superoffice.com/{{tenant}}/api/v1/archive/internalusers?$select=associateDbId,fullName,personId,personEmail HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

###


GET https://{{env}}.superoffice.com/{{tenant}}/api/v1/archive/emailpersonaddress?$entities=email&$select=emailAddress&$filter=personId in (5,6,7,8) HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

###

GET https://europe-001.azure-apim.net/apim/selectcompanies-5f5bd4ab9f0bb6a1c7-5f24ec2e29293bef7d/d026806db4c747c6b1ec4692fcd8f22a/{{tenant}}/api/v1/contact 
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

###

GET https://{{env}}.superoffice.com/{{tenant}}/api/v1/contact/5
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

###


GET https://{{env}}.superoffice.com/{{tenant}}/api/v1/archive/simpleperson/?$select=firstName,lastname&$filter=birthYear between ('1972','1980') and birthMonth between ('1','6') and birthDay between ('1','25')
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

###

GET https://{{env}}.superoffice.com/{{tenant}}/api/v1/archive/simpleperson/?$select=firstName,lastname&$filter=personId eq 61106
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

###

GET https://{{env}}.superoffice.com/{{tenant}}/api/v1/archive/recyclecontact/?$select=name,department&$filter=contactId eq 10855
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

###


GET https://{{env}}.superoffice.com/{{tenant}}/api/v1/archive/recycleperson/?$select=firstName,lastname,personContact/orgnr&$filter=personId eq 61106
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

###

GET https://{{env}}.superoffice.com/{{tenant}}/api/v1/archive/dynamic?$select=person.person_id,person.contact_id&$filter=person.person_id eq 61106 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

###

GET https://{{env}}.superoffice.com/{{tenant}}/api/v1/archive/dynamic?$select=MergeMoveLog.sourceRecord,mergemovelog.mergemovelog_id&$filter=MergeMoveLog.tablenumber eq 5 and MergeMoveLog.registered after '2016-01-01' HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 8A:{{tenant}}.AeACDXrYwFxRg2QynE1lEwcgAgAAcMg1SKeqZtTM7kyaO5aRvRpyQnjA+C06SQesZhUl8nQ7U2DawZ1VvLvuiBaxDDNTPaOWT0E0g6OZ5t2moBkjqREX6Ce4i4Ml6BvNKGLsDMAkiCR6HvEDSoQhSpSjZlVlYEXMRXpAY8Ot3v9PHewXmQyR0/p3Rnzk5VZkQ8xkZnkgcthCKy28uTlbVIjeuBujQcZQLTpc+m+Ur7inX25Bcz2rPyuj8Nupo77HRQi4QwQi7nyCf0gu8xhw5klHL5lnNPnyZ9313uFdr8DXVdo8zjPEapLZi7v0PJztb9cJvo1QJnHPPkHilTc/9JNvOWOgIlh+oOpGncAlNconDEDC+3OAioZ68+/wPEypoXsHCedVP/v5t4jaJS3QSl36+JKCMMXGSu10OTO/v1VsgUOy832KpDWFwaRihSq5XTAGqqBcnH8ynwdVZhmhEadZ+3foPPpkYu7jRJJy7hOpE4eeSlZTZmhmhjBWYH7Dnz4NUfVJEFlzc9L4BLMZXJrd+ldyacNrjt5VFJbzRMTRf+Y0TvZaFAsyLR3Rb5knQkECnpfMHnPCd6+MUnwytxSeOpiJiEQWnZfyVyy6q9NqE84wdOSgWAz86XB1/5k5DPUcgl9ysJVg9qu6GEfrGTBXqc6a4OBXG42LB6u1sQnjMKKimS7APD7mPNJ/jeSDqTaQnI66moGDyxG5+t7lMSn/yb4LyAmmtuHu84C1QiR/2WrH3uTsRIeygPc73urjhGIuK7X4b3XJbrD25DL4fVZ3uIw2


###

GET https://{{env}}.superoffice.com/{{tenant}}/api/v1/archive/dynamic?$select=associate.associate_id,associate.person_id,associate.registered&$filter=associate.registered thisYear&$top=5000 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 8A:{{tenant}}.AZ34i9zkl1aURyE97S9/vSIgAgAAWgCmdOFAKGarzp8Y4r+HvPLG14jQhRNmgt508j2On8Pl1bIbCAF/9+QtDcwUlHyR5kZWCtHIPY02hn1SfV2EoCco9OC/Tpi1KFjDkT6oum5hsM4xCibs38G5ss8zc2wYFUAdWWMiYQJGKCBXtWcu3JmKxoFz1z+VGG4qjqbEnWGSM+8oiqt+ixv4XVyOcF58gDnDtD5wLE3DvGHvNMvKYGQz1e/jYE1rf9nIlQ+PPK4UkMnaENg08BbjyvTsqqUn8laOe29856Q2yP5+21dpkmcewbvohg+pge+nZ2LhGgjo1q0OVQdg9EcHWVClGm02zL0FzWC8GRbnvpqo1yK7vngfqHN7GA3MRzYvBp1ImPlGvNWi3+tivXVrhs4jtLQQibaO4Yd9St1YmLRNmzufflVBflvCUR7WVV0zqK4uZAVat2+BbeV7A2c0ieEb1V7/NV0Fo/FbbIqaH64Lg/kw+OWqqhpB8AqIqsAYvQmt1f7QUha9r5lZjellZjqp7MHN3YtxZkvYXKjGnoMEw/CPEpfUgV8VUAdshpzRlUgJCVBTN3L9GyyNFjcoOLW/dAKH6oivKyqzWiWfDo9CitEwgwAxFmIdlG7yeB6v0ucpaY0UPz6+h31iVQuEPaZQL8EehQjYHfeO7gwqD3fMnF1Abq3buqO7X8avrwUfgpYlXMmXtbJKVpx61/P09zdI/XXvxC8NW9HZuzgbsfXsFdE8Wb60eUhWaTRcE+MlEyaCsJNA2naVXu7fs7j8G8AmZkGQ

###


GET https://{{env}}.superoffice.com/{{tenant}}/api/v1/archive/dynamic?$select=traveltransactionlog.record_id&$filter=tablenumber eq 11 and traveltransactionlog.type eq 4864 and traveltransactionlog.ttime afterTime YOUR_LAST_QUERY_TIME HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 8A:{{tenant}}.AZ34i9zkl1aURyE97S9/vSIgAgAAWgCmdOFAKGarzp8Y4r+HvPLG14jQhRNmgt508j2On8Pl1bIbCAF/9+QtDcwUlHyR5kZWCtHIPY02hn1SfV2EoCco9OC/Tpi1KFjDkT6oum5hsM4xCibs38G5ss8zc2wYFUAdWWMiYQJGKCBXtWcu3JmKxoFz1z+VGG4qjqbEnWGSM+8oiqt+ixv4XVyOcF58gDnDtD5wLE3DvGHvNMvKYGQz1e/jYE1rf9nIlQ+PPK4UkMnaENg08BbjyvTsqqUn8laOe29856Q2yP5+21dpkmcewbvohg+pge+nZ2LhGgjo1q0OVQdg9EcHWVClGm02zL0FzWC8GRbnvpqo1yK7vngfqHN7GA3MRzYvBp1ImPlGvNWi3+tivXVrhs4jtLQQibaO4Yd9St1YmLRNmzufflVBflvCUR7WVV0zqK4uZAVat2+BbeV7A2c0ieEb1V7/NV0Fo/FbbIqaH64Lg/kw+OWqqhpB8AqIqsAYvQmt1f7QUha9r5lZjellZjqp7MHN3YtxZkvYXKjGnoMEw/CPEpfUgV8VUAdshpzRlUgJCVBTN3L9GyyNFjcoOLW/dAKH6oivKyqzWiWfDo9CitEwgwAxFmIdlG7yeB6v0ucpaY0UPz6+h31iVQuEPaZQL8EehQjYHfeO7gwqD3fMnF1Abq3buqO7X8avrwUfgpYlXMmXtbJKVpx61/P09zdI/XXvxC8NW9HZuzgbsfXsFdE8Wb60eUhWaTRcE+MlEyaCsJNA2naVXu7fs7j8G8AmZkGQ

###

GET https://{{env}}.superoffice.com/{{tenant}}/api/v1/archive/dynamic?$select=ticket.id,ticket.title,ticket.created_at&$filter=getAllRows=true&$options=GrandTotal=true HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 8A:{{tenant}}.AZ34i9zkl1aURyE97S9/vSIgAgAAWgCmdOFAKGarzp8Y4r+HvPLG14jQhRNmgt508j2On8Pl1bIbCAF/9+QtDcwUlHyR5kZWCtHIPY02hn1SfV2EoCco9OC/Tpi1KFjDkT6oum5hsM4xCibs38G5ss8zc2wYFUAdWWMiYQJGKCBXtWcu3JmKxoFz1z+VGG4qjqbEnWGSM+8oiqt+ixv4XVyOcF58gDnDtD5wLE3DvGHvNMvKYGQz1e/jYE1rf9nIlQ+PPK4UkMnaENg08BbjyvTsqqUn8laOe29856Q2yP5+21dpkmcewbvohg+pge+nZ2LhGgjo1q0OVQdg9EcHWVClGm02zL0FzWC8GRbnvpqo1yK7vngfqHN7GA3MRzYvBp1ImPlGvNWi3+tivXVrhs4jtLQQibaO4Yd9St1YmLRNmzufflVBflvCUR7WVV0zqK4uZAVat2+BbeV7A2c0ieEb1V7/NV0Fo/FbbIqaH64Lg/kw+OWqqhpB8AqIqsAYvQmt1f7QUha9r5lZjellZjqp7MHN3YtxZkvYXKjGnoMEw/CPEpfUgV8VUAdshpzRlUgJCVBTN3L9GyyNFjcoOLW/dAKH6oivKyqzWiWfDo9CitEwgwAxFmIdlG7yeB6v0ucpaY0UPz6+h31iVQuEPaZQL8EehQjYHfeO7gwqD3fMnF1Abq3buqO7X8avrwUfgpYlXMmXtbJKVpx61/P09zdI/XXvxC8NW9HZuzgbsfXsFdE8Wb60eUhWaTRcE+MlEyaCsJNA2naVXu7fs7j8G8AmZkGQ

###

GET https://{{env}}.superoffice.com/{{tenant}}/api/v1/archive/dynamic?$select=Count(ticket.id):Footer&$filter=getAllRows=true&$options=GrandTotal=true HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 8A:{{tenant}}.AZ34i9zkl1aURyE97S9/vSIgAgAAWgCmdOFAKGarzp8Y4r+HvPLG14jQhRNmgt508j2On8Pl1bIbCAF/9+QtDcwUlHyR5kZWCtHIPY02hn1SfV2EoCco9OC/Tpi1KFjDkT6oum5hsM4xCibs38G5ss8zc2wYFUAdWWMiYQJGKCBXtWcu3JmKxoFz1z+VGG4qjqbEnWGSM+8oiqt+ixv4XVyOcF58gDnDtD5wLE3DvGHvNMvKYGQz1e/jYE1rf9nIlQ+PPK4UkMnaENg08BbjyvTsqqUn8laOe29856Q2yP5+21dpkmcewbvohg+pge+nZ2LhGgjo1q0OVQdg9EcHWVClGm02zL0FzWC8GRbnvpqo1yK7vngfqHN7GA3MRzYvBp1ImPlGvNWi3+tivXVrhs4jtLQQibaO4Yd9St1YmLRNmzufflVBflvCUR7WVV0zqK4uZAVat2+BbeV7A2c0ieEb1V7/NV0Fo/FbbIqaH64Lg/kw+OWqqhpB8AqIqsAYvQmt1f7QUha9r5lZjellZjqp7MHN3YtxZkvYXKjGnoMEw/CPEpfUgV8VUAdshpzRlUgJCVBTN3L9GyyNFjcoOLW/dAKH6oivKyqzWiWfDo9CitEwgwAxFmIdlG7yeB6v0ucpaY0UPz6+h31iVQuEPaZQL8EehQjYHfeO7gwqD3fMnF1Abq3buqO7X8avrwUfgpYlXMmXtbJKVpx61/P09zdI/XXvxC8NW9HZuzgbsfXsFdE8Wb60eUhWaTRcE+MlEyaCsJNA2naVXu7fs7j8G8AmZkGQ


###

GET https://crm.superoffice.com/SuperOffice/api/v1/archive/dynamic?$select=Count(ticket.id):Footer&$filter=getAllRows=true&$options=GrandTotal=true HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Basic dG9ueTo5VGVuRWxldmVuT2Nsb2Nr

###

GET https://crm.superoffice.com/SuperOffice/api/v1/archive/dynamic?$select=Count(associate.associate_id):Footer&$options=GrandTotal=true HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Basic dG9ueTo5VGVuRWxldmVuT2Nsb2Nr

###

GET https://crm.superoffice.com/SuperOffice/api/v1/archive/AllUsers?$entities=all&$select=CountAll(associateDbId):Footer&$options=GrandTotal=true HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Basic dG9ueTo5VGVuRWxldmVuT2Nsb2Nr

###

GET https://crm.superoffice.com/SuperOffice/api/v1/archive/ticket?$select=Count(ticketId):Footer&$options=GrandTotal=true&$top=50000000 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Basic dG9ueTo5VGVuRWxldmVuT2Nsb2Nr

###

POST https://crm.superoffice.com/SuperOffice/api/v1/Agents/Archive/GetArchiveListByColumns?$options=GrandTotal=true HTTP/1.1
Host: sod.superoffice.com:443
Authorization: Basic dG9ueTo5VGVuRWxldmVuT2Nsb2Nr
Accept: application/json
Content-Type: application/json

{
  "ProviderName": "AllUsers",
  "Columns": [
    "associateDbId",
    "Count(associateDbId):HideDetail:Footer"
  ],
  "SortOrder": [
    {
      "Name": "associateDbId",
      "Direction": "ASC"
    }
  ],
  "Restriction": [
    {
      "Name": "associateDbId",
      "Operator": ">",
      "Values": [
        "0"
      ],
      "IsActive": true
    }
  ],
  "Entities": [
    "all"
  ],
  "Page": 0,
  "PageSize": 1000000
}

###

POST https://{{env}}.superoffice.com/{{tenant}}/api/v1/Agents/Archive/GetArchiveListByColumns HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
  "ProviderName": "Person",
  "Columns": [
    "personId",
    "firstName"
  ],
  "SortOrder": [
    {
      "Name": "personId",
      "Direction": "ASC"
    }
  ],
  "Restriction": [
    {
      "Name": "personId",
      "Operator": "=",
      "Values": [
        "25"
      ],
      "IsActive": true
    }
  ],
  "Entities": [
    "person"
  ],
  "Page": 0,
  "PageSize": 1000000
}

###

POST https://{{env}}.superoffice.com/{{tenant}}/api/v1/Agents/Archive/GetArchiveListByColumns2
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "Columns": "Field,blankallowed,active,recordId",
  "ProviderName": "Numbers",
  "Page": 0,
  "PageSize": 200,
  "Entities": "number",
  "SortOrder": "",
  "Restrictions": "getAllRows=1"
}

###

GET https://{{env}}.superoffice.com/{{tenant}}/api/v1/Archive/FindContact?$select=contactId%2Ccode%2Cname,email/emailAddress&$entities=contact HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

###


GET https://{{env}}.superoffice.com/{{tenant}}/api/v1/Archive/FindContact?$select=contactId,name,email/emailAddress&$entities=contact&$filter=contactid gt 0 HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

###


GET https://{{env}}.superoffice.com/{{tenant}}/api/v1/Archive/SimpleContact?$select=email/emailAddress,contactId%2Ccode%2Cname%2CcontactAssociate%2FpersonId%2Ccategory%2Cbusiness%2Corgnr%2Cnumber,contactAssociate/associateDbId HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

###