POST {{api_url}}/v1/Agents/Associate/GetAssociatesByGroup?$select=AssociateId,Name
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

{
  "GroupId": 5,
  "Type": 2
}

# 2 = InternalAssociate
# 4 = SystemAssociate

###


POST {{api_url}}/v1/Agents/MDO/GetList
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

{
  "Name": "Associate",
  "ForceFlatList": false,
  "AdditionalInfo": "",
  "OnlyHistory": false
}

###


POST {{api_url}}/v1/Agents/Archive/GetArchiveListByColumns HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
  "ProviderName": "InternalUsers",
  "Columns": [
    "firstName",
    "lastName",
    "middleName",
    "fullName",
    "personId",
    "title",
    "associateDbId"
  ],
  "SortOrder": [
    {
      "Name": "associateDbId",
      "Direction": "ASC"
    }
  ],
  "Restriction": [
    {
      "Name": "associateDbId",
      "Operator": ">",
      "Values": [
        "0"
      ],
      "IsActive": true
    }
  ],
  "Entities": [
    "all"
  ],
  "Page": 0,
  "PageSize": 1000000
}

###

POST {{api_url}}/v1/Agents/Associate/GetAssociateList
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

[ 3,4,5,6,7,8,9,10 ]

###

GET {{api_url}}/v1/user/currentPrincipal HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

###

GET {{api_url}}/v1/user/currentAssociate HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

###

#Inaccessible online
GET {{api_url}}/v1/user/current HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

###

GET {{api_url}}/v1/archive/dynamic?$select=associate.associate_id,associate.name,associate.lastlogin HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

###

GET {{api_url}}/v1/user/currentToken HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

###