###

GET https://{{env}}.superoffice.com/{{tenant}}/api/v1/contact/28 HTTP/1.1
Authorization: SOTicket {{ticket}}
SO-AppToken: {{client_secret}}
Accept: application/json

###

GET https://{{env}}.superoffice.com/{{tenant}}/api/v1/contact/28 HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

###

GET https://{{env}}.superoffice.com/{{tenant}}/api/v1/contact?$select=name,nameDepartment&$filter=name eq 'Starbucks' and department eq 'Wholesale Coffee Distribution' HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json


###

GET https://{{env}}.superoffice.com/{{tenant}}/api/v1/Contact/2/Persons"
Authorization: Bearer {{token}}
Accept: application/json

###
GET https://{{env}}.superoffice.com/{{tenant}}/api/v1/contact?$select=contactPhone/formattedNumber,url/URLAddress,contactId,category,business,country,number,code,orgnr,stop,registeredBy,registeredDate,nameDepartment,updatedBy,updatedDate,hasInterests&$orderby=contactId&$filter=contactId gt 5000 and contactId lt 10000&$top=5000 HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json
###


GET https://{{env}}.superoffice.com/{{tenant}}/api/v1/contact?$select=contactId,hasInfoText&$orderby=contactId&$filter=contactId in (1,2,3,4,5,6,7,8) HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json


###
GET https://{{env}}.superoffice.com/{{tenant}}/api/v1/contact/5?$select=Name,Department,Emails HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

###

GET https://{{env}}.superoffice.com/{{tenant}}/api/v1/Contact/Duplicates/Super%20+ HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

###


POST https://{{env}}.superoffice.com/{{tenant}}/api/v1/Agents/Contact/GetDuplicates HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json; charset=utf-8
Content-Type: application/json; charset=utf-8

{
  "Name": "Super +"
}
###

GET https://{{env}}.superoffice.com/{{tenant}}/api/v1/MDOList/contint?query=contactId eq 13418 HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

###

GET https://{{env}}.superoffice.com/{{tenant}}/api/v1/archive/dynamic?$select=contactinterest.contact_id,contactinterest.cinterest_idx&$filter=contactinterest.contact_id in (13418,13921) HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

###

GET https://{{env}}.superoffice.com/{{tenant}}/api/v1/contact/3 HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

###




GET https://{{env}}.superoffice.com/{{tenant}}/api/v1/contact?$filter=name begins Su HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

###

@filter = Archive/Dynamic?$select=contact.contact_id,contact.department&$filter=contact.name contains 'super' or contact.department contains 'awesome' or contains(contact.number2, 'Persons AS')


GET https://{{env}}.superoffice.com/{{tenant}}/api/v1/Archive/Dynamic?$select=contact.name,contact.department,contact.number2&$filter=(contact.name contains 'white' or contact.number2 contains 10110) and contact.contact_id notOneOf (32,67) HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

###

POST https://{{env}}.superoffice.com/{{tenant}}/api/v1/contact HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

{
  "Name": "Company For Testing",
  "Department": "Operations",
}

###
POST https://{{env}}.superoffice.com/{{tenant}}/api/v1/contact HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

{
  "ContactId": 0,
  "Name": "Company With Phones Three",
  "Department": "Funtime",
  "Number2": "10114",
  "Business": {
    "Id": 2,
  },
  "Category": {
    "Id": 4,
  },
  "Country": {
    "CountryId": 826,
  },
  "Phones": [
    {
      "Value": "+479514542",
      "Description": "Mobile"
    }
  ],
}

###

GET https://{{env}}.superoffice.com/{{tenant}}/api/v1/contact/5 HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

###


GET https://{{env}}.superoffice.com/{{tenant}}/api/v1/contact?$select=contactId,name&$filter=contactExtra/x_hassupportagreement eq 0 HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

###
PATCH https://{{env}}.superoffice.com/{{tenant}}/api/v1/contact/28 HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

[ { "op": "replace", "path": "/Department", "value": "foo" } ]

###
PATCH https://{{env}}.superoffice.com/{{tenant}}/api/v1/contact/28 HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

[
  {
    "op": "replace",
    "path": "/UpdatedBy",
    "value": {
      "AssociateId": 6
    }
  }
]

###
PATCH https://{{env}}.superoffice.com/{{tenant}}/api/v1/contact/5 HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

[
    {
      "op": "replace",
      "path": "Department",
      "value": "Operations"
    },
    {
        "op": "replace",
        "path": "Phones",
        "value": [
          {
            "Value":"99887755"
          }
        ]
    }
]

###

PATCH https://{{env}}.superoffice.com/{{tenant}}/api/v1/contact/5 HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

[ 
  {
    "op": "replace",
    "path": "Department",
    "value": "Operations"
  },
  {
    "op": "replace",
    "path": "Phones",
    "value": [
      {
        "Value":"99887755"
      }
    ]
  },
  { 
    "op": "replace", 
    "path": "CustomFields", 
    "value": {
        "x_sale": "5",
        "SuperOffice:2": "42",
        "SuperOffice:9": "Testing2",
    }
  }
]

###

PATCH https://{{env}}.superoffice.com/{{tenant}}/api/v1/contact/5 HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

[ 
    { 
        "op": "replace", 
        "path": "CustomFields", 
        "value": {
            "x_sale": "5",
            "SuperOffice:2": "42",
            "SuperOffice:9": "Testing2",
        }
    }
]

###



GET https://{{env}}.superoffice.com/{{tenant}}/api/v1/contact?$select=name&$filter=contactInterestIds oneOf (2,3) HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

###
GET https://{{env}}.superoffice.com/{{tenant}}/api/v1/contact?$select=name&$filter=hasInterests set true HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

###


GET https://{{env}}.superoffice.com/{{tenant}}/api/v1/Contact?$filter=phone/formattedNumber is '+4790168242' HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

###