@token=8A:
@tenant=Cust12345
@env=sod
@ticket=7T:
@app_secret=


@qry = KB_ENTRY.title,KB_ENTRY.question,KB_ENTRY.answer,KB_ENTRY.category_id,KB_ENTRY.access_level
GET https://{{env}}.superoffice.com/{{tenant}}/api/v1/Archive/Dynamic?$select=KB_ENTRY.title,KB_ENTRY.question,KB_ENTRY.answer,KB_ENTRY.category_id,KB_ENTRY.access_level HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

###
