GET {{api_url}}/v1/MDOList/persint HTTP/1.1
Authorization: Bearer {{access_token}}
Accept: application/json

###

GET {{api_url}}/v1/MDOList/contint HTTP/1.1
Authorization: Bearer {{access_token}}
Accept: application/json

###

PATCH {{api_url}}/v1/Person/1 HTTP/1.1
Authorization: Bearer {{access_token}}
Content-Type: application/json

[
  {  
    "op": "replace",
    "path": "Interests",
    "value": [
      {     
        "Id": "10",
        "Selected": true
      }
    ]
  }
]

###

PATCH {{api_url}}/v1/Person/1 HTTP/1.1
Authorization: Bearer {{access_token}}
Content-Type: application/json

 { 
  "Interests": [ 
    { 
      "Id": 10,
      "Selected": true 
    }
  ] 
}

###

PATCH {{api_url}}/v1/Contact/7 HTTP/1.1
Authorization: Bearer {{access_token}}
Content-Type: application/json

[
  { 
    "op": "replace", 
    "path": "/Interests/0/Selected", 
    "value": true 
  },
  { 
    "op": "replace", 
    "path": "/Interests/2", 
    "value": 
    { 
      "Id": 3, 
      "Selected": true 
    }
  }
]



###

# Get all selected interests for a person by person id
@query = person.(personinterest->person_id).pinterest_idx,person.(personinterest->person_id).pinterest_idx.name
@filter = person.person_id in (10,23) 
GET {{api_url}}/v1/archive/dynamic?$select={{query}}&$filter={{filter}} HTTP/1.1
Authorization: Bearer {{access_token}}
Content-Type: application/json
Accept: application/json

###

# Get all selected interests for multiple people, use the "in" operator.

@query = person.(personinterest->person_id).pinterest_idx,person.(personinterest->person_id).pinterest_idx.name
@filter = person.person_id in (10,23) 

GET {{api_url}}/v1/archive/dynamic?$select={{query}}&$filter={{filter}} HTTP/1.1
Authorization: Bearer {{access_token}}
Content-Type: application/json
Accept: application/json