@tenant=Cust12345
@env=sod
@token=7T:
@app_secret=

POST https://{{env}}.superoffice.com/{{tenant}}/api/v1/Agents/DatabaseTable/Insert HTTP/1.1
Authorization: SOTicket {{token}}
SO-AppToken: {{app_secret}}
Accept: application/json
Content-Type: application/json

{
  "TableName": "project",
  "Columns": [
    "name",
    "type_idx",
    "associate_id",
    "activeLinks"
  ],
  "Data": [
    [
      "Project Test One",
      "2",
      "10",
      0
    ],
    [
      "Project Test 2",
      "4",
      "12",
      0
    ],
    [
      "Project Test 3",
      "2",
      "12",
      0
    ]
  ]
}

###

POST https://{{env}}.superoffice.com/{{tenant}}/api/v1/Agents/DatabaseTable/Insert HTTP/1.1
Authorization: SOTicket {{token}}
SO-AppToken: {{app_secret}}
Accept: application/json
Content-Type: application/json

{
  "TableName": "projectmember",
  "Columns": [
    "project_id",
    "contact_id",
    "person_id",
    "mtype_idx"
  ],
  "Data": [
    [
      "246010",
      "25",
      "214",
      "3"
    ],
    [
      "246010",
      "25",
      "215",
      "3"
    ],
    [
      "246010",
      "25",
      "216",
      "3"
    ]
  ]
}

###

POST https://{{env}}.superoffice.com/{{tenant}}/api/v1/Agents/DatabaseTable/Insert HTTP/1.1
Authorization: SOTicket {{token}}
SO-AppToken: {{app_secret}}
Accept: application/json
Content-Type: application/json

{
  "TableName": "sale",
  "Columns": [
    "associate_id",
    "group_idx",
    "contact_id",
    "person_id",
    "saledate",
    "amount",
    "probability_idx",
    "appointment_id",
    "project_id",
    "activeLinks"

  ],
  "Data": [
    [
      "5",
      "5",
      "30",
      "257",
      "[D:09.11.2021]",
      "986.00",
      "1",
      "0",
      "246010",
      "0"
    ],
    [
      "5",
      "5",
      "32",
      "264",
      "[D:10.11.2021]",
      "3000",
      "1",
      "0",
      "246010",
      "0"
    ],
    [
      "5",
      "5",
      "50",
      "287",
      "[D:11.11.2021]",
      "23000",
      "2",
      "0",
      "246010",
      "0"
    ]
  ]
}

###

POST https://{{env}}.superoffice.com/{{tenant}}/api/v1/Agents/DatabaseTable/Insert HTTP/1.1
Authorization: SOTicket {{token}}
SO-AppToken: {{app_secret}}
Accept: application/json
Content-Type: application/json

{
  "TableName": "appointment",
  "Columns": [
    "associate_id",
    "group_idx",
    "contact_id",
    "person_id",
    "done",
    "do_by",
    "task_idx",
    "activeLinks"

  ],
  "Data": [
    [
      "5",
      "5",
      "30",
      "257",
      "[D:09.11.2021]",
      "[D:09.11.2021]",
      "1",
      "0"
    ],
    [
      "5",
      "5",
      "32",
      "264",
      "[D:10.11.2021]",
      "[D:10.11.2021]",
      "1",
      "0"
    ]
  ]
}

###