@ticketId=1
@number2=1
@log_ticket_custId=1
@log_id=1

### GetTicketLog - Get log data by ticketId
GET {{api_url}}/v1/archive/dynamic?$select=y_log.id,y_log.x_ticket,y_log.x_ticket.title,y_log.x_ticket.status,y_log.x_ticket.ticket_status,y_log.x_ticket.ticket_status.name,y_log.x_ticket.cust_id,y_log.x_ticket.cust_id.fullName,y_log.x_ticket.cust_id.emailAddress,y_log.x_ticket.cust_id.contact_id,y_log.x_ticket.cust_id.contact_id.name,y_log.x_ticket.cust_id.contact_id.orgNr,y_log.x_ticket.cust_id.contact_id.userdef_id.long34,y_log.x_ticket.cust_id.direct/formattedNumber,y_log.x_ticket.cust_id.mobile/formattedNumber,y_log.x_ticket.x_cause_of_damage,y_log.x_ticket.x_description_of_damage,y_log.x_ticket.x_skadedato,y_log.x_ticket.x_selskapsnr,y_log.x_ticket.x_reported_by,y_log.x_ticket.x_apartments_json,y_log.x_registered,y_log.x_closed&$filter=y_log.x_ticket eq {{ticketId}} HTTP/1.1
Authorization: Bearer {{access_token}}
Accept: application/json
