###
GET https://{{env}}.superoffice.com/{{tenant}}/api/v1/contact?$select=name,associateId,contactAssociate/fullName HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

###

#- Boolean --------------------------------------------------

GET https://{{env}}.superoffice.com/{{tenant}}/api/v1/contact?$select=name,associateId,contactAssociate/fullName&$filter=hasInterests set true HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

###

#- String --------------------------------------------------
GET https://{{env}}.superoffice.com/{{tenant}}/api/v1/contact?$select=name,associateId,contactAssociate/fullName&$filter=name begins 'S' HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

###

GET https://{{env}}.superoffice.com/{{tenant}}/api/v1/contact?$select=name,associateId,contactAssociate/fullName&$filter=name is 'Testing null Orgnr' HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

###

GET https://{{env}}.superoffice.com/{{tenant}}/api/v1/contact?$select=name,associateId,contactAssociate/fullName&$filter=name contains 'Orgnr' HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

###

GET https://{{env}}.superoffice.com/{{tenant}}/api/v1/contact?$select=name,associateId,contactAssociate/fullName&$filter=name notBegins 'S' HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

###

GET https://{{env}}.superoffice.com/{{tenant}}/api/v1/contact?$select=name,associateId,contactAssociate/fullName&$filter=name notContains 'Owl' HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

###

# Fails.

GET https://{{env}}.superoffice.com/{{tenant}}/api/v1/contact?$select=name,associateId,contactAssociate/fullName&$filter=name notEnds 'Landing' HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

###

GET https://{{env}}.superoffice.com/{{tenant}}/api/v1/contact?$select=name,associateId,contactAssociate/fullName&$filter=name isNot 'SuperOffice Software Limited' HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

###

#- between
GET https://{{env}}.superoffice.com/{{tenant}}/api/v1/contact?$select=name,associateId,contactAssociate/fullName&$filter=name between ('A','S') HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

###

#- Numbers --------------------------------------------------------------

GET https://{{env}}.superoffice.com/{{tenant}}/api/v1/contact?$select=name,associateId,contactAssociate/fullName&$filter=contactId = 5 HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

###

GET https://{{env}}.superoffice.com/{{tenant}}/api/v1/contact?$select=name,associateId,contactAssociate/fullName&$filter=contactId eq 2 HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

###

GET https://{{env}}.superoffice.com/{{tenant}}/api/v1/contact?$select=name,associateId,contactAssociate/fullName&$filter=contactId ne 2 HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

###

# Fails

GET https://{{env}}.superoffice.com/{{tenant}}/api/v1/contact?$select=name,associateId,contactAssociate/fullName&$filter=contactId le 5 HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

###

GET https://{{env}}.superoffice.com/{{tenant}}/api/v1/contact?$select=name,associateId,contactAssociate/fullName&$filter=contactId lt 5 HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

###

GET https://{{env}}.superoffice.com/{{tenant}}/api/v1/contact?$select=name,associateId,contactAssociate/fullName&$filter=contactId gt 5 HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

###

# Fails

GET https://{{env}}.superoffice.com/{{tenant}}/api/v1/contact?$select=name,associateId,contactAssociate/fullName&$filter=contactId ge 5 HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

###


GET https://{{env}}.superoffice.com/{{tenant}}/api/v1/contact?$select=name,associateId,contactAssociate/fullName&$filter=contactId set 5 HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

###

GET https://{{env}}.superoffice.com/{{tenant}}/api/v1/contact?$select=name,associateId,contactAssociate/fullName&$filter=contactId equals 5 HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

###

GET https://{{env}}.superoffice.com/{{tenant}}/api/v1/contact?$select=name,associateId,contactAssociate/fullName&$filter=contactId greater 5 HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

###

GET https://{{env}}.superoffice.com/{{tenant}}/api/v1/contact?$select=name,associateId,contactAssociate/fullName&$filter=contactId less 5 HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

###

GET https://{{env}}.superoffice.com/{{tenant}}/api/v1/contact?$select=name,associateId,contactAssociate/fullName&$filter=contactId unequals 5 HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

###

#-- Date ------------------------------------------------

#-All-
GET https://{{env}}.superoffice.com/{{tenant}}/api/v1/appointment?$select=type,text,contact/name HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

###

GET https://{{env}}.superoffice.com/{{tenant}}/api/v1/appointment?$select=date,type,text,contact/name?&$filter=date before '2020-05-28' HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

###

#-after 

GET https://{{env}}.superoffice.com/{{tenant}}/api/v1/appointment?$select=type,text,contact/name?&$filter=date after '2020-05-28' HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

###

#- date
GET https://{{env}}.superoffice.com/{{tenant}}/api/v1/appointment?$select=date, type,text,contact/name?&$filter=date date '2020-05-28' HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

###

#- between
GET https://{{env}}.superoffice.com/{{tenant}}/api/v1/appointment?$select=date, type,text,contact/name?&$filter=date between ('2020-05-11','2020-05-31') HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

###

#- beforeorEqual
GET https://{{env}}.superoffice.com/{{tenant}}/api/v1/appointment?$select=type,text,contact/name?&$filter=date beforeOrEqual '2020-05-28' HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

###

#- dateTime
GET https://{{env}}.superoffice.com/{{tenant}}/api/v1/appointment?$select=date,type,text,contact/name?&$filter=date dateTime '2020-05-28T15:00:00' HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

###

#- DateTime ---------------------------------------------

#- beforeTime
GET https://{{env}}.superoffice.com/{{tenant}}/api/v1/appointment?$select=date,type,text,contact/name?&$filter=date beforeTime '2020-05-28T15:00:00' HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

###

#- afterTime
GET https://{{env}}.superoffice.com/{{tenant}}/api/v1/archive/dynamic?$select=traveltransactionlog.record_id,traveltransactionlog.ttime,traveltransactionlog.tablenumber&$filter=traveltransactionlog.ttime afterTime '2010-12-02Z12:00:00' and traveltransactionlog.tablenumber eq 11&$inlineCount=true HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

###

#- beforeTime
GET https://{{env}}.superoffice.com/{{tenant}}/api/v1/appointment?$select=date,type,text,contact/name?&$filter=date beforeTime '2020-05-28T15:00:00' HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

###

#- Unary day ------------------------------------------------

#- beforeToday
GET https://{{env}}.superoffice.com/{{tenant}}/api/v1/appointment?$select=date,type,text,contact/name?&$filter=date beforeToday HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

###

#- today
GET https://{{env}}.superoffice.com/{{tenant}}/api/v1/appointment?$select=date,type,text,contact/name?&$filter=date today HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

###

#- afterToday
GET https://{{env}}.superoffice.com/{{tenant}}/api/v1/appointment?$select=date,type,text,contact/name?&$filter=date afterToday HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

###

#- Unary Weeks ---------------------------------------------

#- lastWeek
GET https://{{env}}.superoffice.com/{{tenant}}/api/v1/appointment?$select=date,type,text,contact/name?&$filter=date lastWeek HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

###

#- thisWeek
GET https://{{env}}.superoffice.com/{{tenant}}/api/v1/appointment?$select=date,type,text,contact/name?&$filter=date thisWeek HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

###

#- nextWeek
GET https://{{env}}.superoffice.com/{{tenant}}/api/v1/appointment?$select=date,type,text,contact/name?&$filter=date nextWeek HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

###

#- Months --------------------------------------------------

#- lastMonth
GET https://{{env}}.superoffice.com/{{tenant}}/api/v1/appointment?$select=date,type,text,contact/name?&$filter=date lastMonth HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

###

#- thisMonth
GET https://{{env}}.superoffice.com/{{tenant}}/api/v1/appointment?$select=date,type,text,contact/name?&$filter=date thisMonth HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

###

#- nextMonth
GET https://{{env}}.superoffice.com/{{tenant}}/api/v1/appointment?$select=date,type,text,contact/name?&$filter=date nextMonth HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

###

#- Quarters --------------------------------------------------

#- lastQuarter
GET https://{{env}}.superoffice.com/{{tenant}}/api/v1/appointment?$select=date,type,text,contact/name?&$filter=date lastQuarter HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

###

#- thisQuarter
GET https://{{env}}.superoffice.com/{{tenant}}/api/v1/appointment?$select=date,type,text,contact/name?&$filter=date thisQuarter HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

###

#- nextQuarter
GET https://{{env}}.superoffice.com/{{tenant}}/api/v1/appointment?$select=date,type,text,contact/name?&$filter=date nextQuarter HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

###

#- Year --------------------------------------------------

#- thisHalf
GET https://{{env}}.superoffice.com/{{tenant}}/api/v1/appointment?$select=date,type,text,contact/name?&$filter=date thisHalf HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

###

#- thisYear
GET https://{{env}}.superoffice.com/{{tenant}}/api/v1/appointment?$select=date,type,text,contact/name?&$filter=date thisYear HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

###

#- Associate --------------------------------------------------

#- associateIsOneOf
GET https://{{env}}.superoffice.com/{{tenant}}/api/v1/contact?$select=name,associateId&$filter=registeredBy associateIsOneOf (1,6) HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

###


#- associateIsNotOneOf
GET https://{{env}}.superoffice.com/{{tenant}}/api/v1/contact?$select=name,associateId&$filter=registeredBy associateIsNotOneOf (1,6) HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

###

#- Lists --------------------------------------------------

#- equals
GET https://{{env}}.superoffice.com/{{tenant}}/api/v1/contact?$select=name,associateId&$filter=category equals 4 HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

###

#- oneOf
GET https://{{env}}.superoffice.com/{{tenant}}/api/v1/contact?$select=name,associateId&$filter=category oneOf (3,6) HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

###


#- notOneOf
GET https://{{env}}.superoffice.com/{{tenant}}/api/v1/contact?$select=name,associateId,category&$filter=category notOneOf (3,6) HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

###
