### Request refresh token

POST https://sod.superoffice.com/login/common/oauth/tokens?grant_type={{grantType}}&client_id={{clientId}}&client_secret={{clientSecret}}&redirect_uri={{redirectUri}}&refresh_token={{refresh_token}}
Accept: application/json
