# Get the list of Typical Search entities to generate Typical Search buttons.
GET {{api_url}}/v1/MDOList/SelectionMemberTypeV2 HTTP/1.1
Authorization: Bearer {{access_token}}
Content-Type: application/json
Accept: application/json

###

# SAME AS ABOVE!!! *********************************************************

# Get the list of Typical Search entities to generate Typical Search buttons.
POST {{api_url}}/v1/Agents/MDO/GetList HTTP/1.1
Authorization: Bearer {{access_token}}
Accept: application/json; charset=utf-8
Accept-Language: en
Content-Type: application/json; charset=utf-8

{
  "Name": "selectionmembertypev2",
  "ForceFlatList": true,
  "AdditionalInfo": "",
  "OnlyHistory": false
}

###

# Get the list of Typical Searchs for contact.
GET {{api_url}}/v1/MDOList/typicalSearch/selectable?additional=contact HTTP/1.1
Authorization: Bearer {{access_token}}
Accept: application/json
Accept-Language: en


###

# SAME AS ABOVE!!! *********************************************************

# Get the list of Typical Searchs for contact.
POST {{api_url}}/v1/Agents/MDO/GetList HTTP/1.1
Authorization: Bearer {{access_token}}
Content-Type: application/json
Accept: application/json
Accept-Language: en

{
  "Name": "typicalSearch",
  "ForceFlatList": true,
  "AdditionalInfo": "contact",
  "OnlyHistory": false
}


###


# Get search Archive Provider for entity by typical search id.

# NO REST equivalent!

POST {{api_url}}/v1/Agents/Selection/GetSelectionForFind HTTP/1.1
Authorization: Bearer {{access_token}}
Content-Type: application/json
Accept: application/json

{
  "EntityName": "quoteline",
  "TypicalSearchId": 2
}

###


POST {{api_url}}/v1/Agents/Selection/GetSelectionForFind HTTP/1.1
Authorization: Bearer {{access_token}}
Content-Type: application/json
Accept: application/json

{
  "EntityName": "person",
  "TypicalSearchId": 0
}

###


POST {{api_url}}/v1/Agents/Selection/GetSelectionForFind HTTP/1.1
Authorization: Bearer {{access_token}}
Content-Type: application/json
Accept: application/json

{
  "EntityName": "sale",
  "TypicalSearchId": 0
}

###


POST {{api_url}}/v1/Agents/Selection/GetSelectionForFind HTTP/1.1
Authorization: Bearer {{access_token}}
Content-Type: application/json
Accept: application/json

{
  "EntityName": "project",
  "TypicalSearchId": 0
}

###

# Load Selection filters by provider name.
# MDOAgent.GetList( name: "archiveRestrictionColumns:" + providerName  )
#                          archiveRestrictionColumns:{providername}

# SAINT must be enabled to get SAINT fields in this list!

GET {{api_url}}/v1/MDOList/archiveRestrictionColumns:ContactPersonDynamicSelectionV2 HTTP/1.1
Authorization: Bearer {{access_token}}
Accept: application/json
Accept-Language: en

###

GET {{api_url}}/v1/MDOList/archiveColumns:ContactPersonDynamicSelectionV2 HTTP/1.1
Authorization: Bearer {{access_token}}
Accept: application/json
Accept-Language: en

###



GET {{api_url}}/v1/MDOList/archiveEntities:ContactPersonDynamicSelectionV2 HTTP/1.1
Authorization: Bearer {{access_token}}
Accept: application/json
Accept-Language: en

###


POST {{api_url}}/v1/Agents/MDO/GetList HTTP/1.1
Authorization: Bearer {{access_token}}
Content-Type: application/json
Accept: application/json

{
  "Name": "archiveEntities:ContactPersonDynamicSelectionV2",
  "ForceFlatList": true,
  "AdditionalInfo": "",
  "OnlyHistory": false
}

###

# Gets the saved criterias for the current selection. (SelectionAgent.GetDynamicSelectionCriteriaGroups)
# Archive Provider: ContactPersonDynamicSelectionV2
# Selection ID: 21

POST {{api_url}}/v1/Agents/Selection/GetDynamicSelectionCriteriaGroups HTTP/1.1
Authorization: Bearer {{access_token}}
Content-Type: application/json
Accept: application/json

{
  "SelectionId": "21",
}

###

# SAME AS ABOVE!!! *********************************************************

# Gets the saved criterias for the current selection. (SelectionAgent.GetDynamicSelectionCriteriaGroups)
# Archive Provider: ContactPersonDynamicSelectionV2
# Selection ID: 21

GET {{api_url}}/v1/Selection/28/CriteriaGroups HTTP/1.1
Authorization: Bearer {{access_token}}
Accept: application/json

###

# Gets extended information about the named filter
# most importantly the names of the operators, and sub-restrictions for SAINT-filters.  

# DesiredColumnNames: filter-name, 
# ProviderName: providerName, 
# StorageKey: ”selection”+selectionId, 
# StorageType: ”criteria” 

POST {{api_url}}/v1/Agents/Find/GetSpecifiedCriteriaInformationWithDefaults HTTP/1.1
Authorization: Bearer {{access_token}}
Content-Type: application/json
Accept: application/json

{
  "DesiredColumnNames": ["firstName", "lastName"],
  "ProviderName": "ContactPersonDynamicSelectionV2",
  "StorageKey": "selection=0",
  "StorageType": "criteria"
}

###

# Get list of operators for given filter's datatype. Cached. 
# -----------------------------------------------------------------------

# Get the restriction operators (non-lists).
# bool, date, datetime, decimal, int,positiveString, string, stringorPK

# Get the restriction operators (lists).
# associate, ejUser, intArray, listAll, listAny, listInterest, userGroup

GET {{api_url}}/v1/MDOList/restrictionOperators/selectable?additional=positiveString HTTP/1.1
Authorization: Bearer {{access_token}}
Content-Type: application/json
Accept: application/json
Accept-Language: en

###

POST {{api_url}}/v1/Agents/MDO/GetList HTTP/1.1
Authorization: Bearer {{access_token}}
Accept: application/json; charset=utf-8
Content-Type: application/json; charset=utf-8
Accept-Language: en

{
  "Name": "restrictionOperators",
  "ForceFlatList": true,
  "AdditionalInfo": "positiveString",
  "OnlyHistory": false
}

###

POST {{api_url}}/v1/Agents/Archive/GetAvailableColumns
Authorization: Bearer {{access_token}}
Accept: application/json; charset=utf-8
Accept-Language: en
Content-Type: application/json; charset=utf-8

{
  "ProviderName": "ContactPersonDynamicSelectionV2",
  "Context": ""
}

###

# Get list of category items. 

GET {{api_url}}/v1/MDOList/Category HTTP/1.1
Authorization: Bearer {{access_token}}
Content-Type: application/json
Accept: application/json

###

GET {{api_url}}/v1/Selection/28/CriteriaGroups HTTP/1.1
Authorization: Bearer {{access_token}}
Content-Type: application/json
Accept: application/json

###

PUT {{api_url}}/v1/Selection/24/CriteriaGroups HTTP/1.1
Authorization: Bearer {{access_token}}
Content-Type: application/json
Accept: application/json

[
  {
    "Name": "0",
    "Description": "",
    "Rank": 0,
    "Restrictions": [
      {
        "Name": "firstName",
        "Operator": "begins",
        "Values": [
          "B"
        ],
        "DisplayValues": [
          "B"
        ],
        "ColumnInfo": {
          "DisplayName": "[SR_PERSONARCHIVE_FIRSTNAME]",
          "DisplayTooltip": "[SR_PERSONARCHIVE_FIRSTNAME_TOOLTIP]",
          "DisplayType": "string",
          "CanOrderBy": true,
          "Name": "firstName",
          "CanRestrictBy": true,
          "RestrictionType": "string",
          "RestrictionListName": null,
          "IsVisible": true,
          "ExtraInfo": "",
          "Width": "20%",
          "IconHint": "Person",
          "HeadingIconHint": ""
        },
        "IsActive": true,
        "SubRestrictions": null,
        "InterParenthesis": 0,
        "InterOperator": "And",
        "UniqueHash": 939057318
      },
      {
        "Name": "lastName",
        "Operator": "begins",
        "Values": [
          "Y"
        ],
        "DisplayValues": [
          "Y"
        ],
        "ColumnInfo": {
          "DisplayName": "[SR_PERSONARCHIVE_LASTNAME]",
          "DisplayTooltip": "[SR_PERSONARCHIVE_LASTNAME_TOOLTIP]",
          "DisplayType": "string",
          "CanOrderBy": true,
          "Name": "lastName",
          "CanRestrictBy": true,
          "RestrictionType": "string",
          "RestrictionListName": null,
          "IsVisible": true,
          "ExtraInfo": "",
          "Width": "20%",
          "IconHint": "Person",
          "HeadingIconHint": ""
        },
        "IsActive": true,
        "SubRestrictions": null,
        "InterParenthesis": 0,
        "InterOperator": "And",
        "UniqueHash": -588059390
      }
    ]
  },
  {
    "Name": "1",
    "Description": "",
    "Rank": 1,
    "Restrictions": [
      {
        "Name": "firstName",
        "Operator": "begins",
        "Values": [
          "R"
        ],
        "DisplayValues": [
          "R"
        ],
        "ColumnInfo": {
          "DisplayName": "[SR_PERSONARCHIVE_FIRSTNAME]",
          "DisplayTooltip": "[SR_PERSONARCHIVE_FIRSTNAME_TOOLTIP]",
          "DisplayType": "string",
          "CanOrderBy": true,
          "Name": "firstName",
          "CanRestrictBy": true,
          "RestrictionType": "string",
          "RestrictionListName": null,
          "IsVisible": true,
          "ExtraInfo": "",
          "Width": "20%",
          "IconHint": "Person",
          "HeadingIconHint": ""
        },
        "IsActive": true,
        "SubRestrictions": null,
        "InterParenthesis": 0,
        "InterOperator": "And",
        "UniqueHash": 939057318
      },
      {
        "Name": "lastName",
        "Operator": "begins",
        "Values": [
          "Y"
        ],
        "DisplayValues": [
          "Y"
        ],
        "ColumnInfo": {
          "DisplayName": "[SR_PERSONARCHIVE_LASTNAME]",
          "DisplayTooltip": "[SR_PERSONARCHIVE_LASTNAME_TOOLTIP]",
          "DisplayType": "string",
          "CanOrderBy": true,
          "Name": "lastName",
          "CanRestrictBy": true,
          "RestrictionType": "string",
          "RestrictionListName": null,
          "IsVisible": true,
          "ExtraInfo": "",
          "Width": "20%",
          "IconHint": "Person",
          "HeadingIconHint": ""
        },
        "IsActive": true,
        "SubRestrictions": null,
        "InterParenthesis": 0,
        "InterOperator": "And",
        "UniqueHash": -588059390
      }
    ]
  }
]
###
POST {{api_url}}/v1/Agents/Selection/SetDynamicSelectionCriteriaGroups
Authorization: Bearer {{access_token}}
Accept: application/json; charset=utf-8
Content-Type: application/json; charset=utf-8
Accept-Language: en

{
  "SelectionId": 24,
  "Criteria": [
    {
      "Name": "0",
      "Description": "",
      "Rank": 0,
      "Restrictions": [
        {
          "Name": "firstName",
          "Operator": "begins",
          "Values": [
            "T"
          ],
          "DisplayValues": [
            "T"
          ],
          "ColumnInfo": {
            "DisplayName": "[SR_PERSONARCHIVE_FIRSTNAME]",
            "DisplayTooltip": "[SR_PERSONARCHIVE_FIRSTNAME_TOOLTIP]",
            "DisplayType": "string",
            "CanOrderBy": true,
            "Name": "firstName",
            "CanRestrictBy": true,
            "RestrictionType": "string",
            "RestrictionListName": null,
            "IsVisible": true,
            "ExtraInfo": "",
            "Width": "20%",
            "IconHint": "Person",
            "HeadingIconHint": ""
          },
          "IsActive": true,
          "SubRestrictions": null,
          "InterParenthesis": 0,
          "InterOperator": "And",
          "UniqueHash": 939057318
        },
        {
          "Name": "lastName",
          "Operator": "begins",
          "Values": [
            "Y"
          ],
          "DisplayValues": [
            "Y"
          ],
          "ColumnInfo": {
            "DisplayName": "[SR_PERSONARCHIVE_LASTNAME]",
            "DisplayTooltip": "[SR_PERSONARCHIVE_LASTNAME_TOOLTIP]",
            "DisplayType": "string",
            "CanOrderBy": true,
            "Name": "lastName",
            "CanRestrictBy": true,
            "RestrictionType": "string",
            "RestrictionListName": null,
            "IsVisible": true,
            "ExtraInfo": "",
            "Width": "20%",
            "IconHint": "Person",
            "HeadingIconHint": ""
          },
          "IsActive": true,
          "SubRestrictions": null,
          "InterParenthesis": 0,
          "InterOperator": "And",
          "UniqueHash": -588059390
        }
      ]
    },
    {
      "Name": "1",
      "Description": "",
      "Rank": 1,
      "Restrictions": [
        {
          "Name": "firstName",
          "Operator": "begins",
          "Values": [
            "R"
          ],
          "DisplayValues": [
            "R"
          ],
          "ColumnInfo": {
            "DisplayName": "[SR_PERSONARCHIVE_FIRSTNAME]",
            "DisplayTooltip": "[SR_PERSONARCHIVE_FIRSTNAME_TOOLTIP]",
            "DisplayType": "string",
            "CanOrderBy": true,
            "Name": "firstName",
            "CanRestrictBy": true,
            "RestrictionType": "string",
            "RestrictionListName": null,
            "IsVisible": true,
            "ExtraInfo": "",
            "Width": "20%",
            "IconHint": "Person",
            "HeadingIconHint": ""
          },
          "IsActive": true,
          "SubRestrictions": null,
          "InterParenthesis": 0,
          "InterOperator": "And",
          "UniqueHash": 939057318
        },
        {
          "Name": "lastName",
          "Operator": "begins",
          "Values": [
            "Y"
          ],
          "DisplayValues": [
            "Y"
          ],
          "ColumnInfo": {
            "DisplayName": "[SR_PERSONARCHIVE_LASTNAME]",
            "DisplayTooltip": "[SR_PERSONARCHIVE_LASTNAME_TOOLTIP]",
            "DisplayType": "string",
            "CanOrderBy": true,
            "Name": "lastName",
            "CanRestrictBy": true,
            "RestrictionType": "string",
            "RestrictionListName": null,
            "IsVisible": true,
            "ExtraInfo": "",
            "Width": "20%",
            "IconHint": "Person",
            "HeadingIconHint": ""
          },
          "IsActive": true,
          "SubRestrictions": null,
          "InterParenthesis": 0,
          "InterOperator": "And",
          "UniqueHash": -588059390
        }
      ]
    }
  ]
}
###

POST {{api_url}}/v1/Agents/Selection/GetSelectionMembersArchiveRows HTTP/1.1
Authorization: Bearer {{access_token}}
Content-Type: application/json
Accept: application/json

{
  "SelectionId": "18",
  "Select": "contactId,name,personId,category,categoryId"
}

###

POST {{api_url}}/v1/Agents/Selection/CreateDefaultSelectionEntity HTTP/1.1
Authorization: Bearer {{access_token}}
Accept: application/json

###


GET {{api_url}}/v1/Selection/default HTTP/1.1
Authorization: Bearer {{access_token}}
Accept: application/json

###

POST {{api_url}}/v1/Agents/Selection/GetSelectionEntity?selectionEntityId=18 HTTP/1.1
Authorization: Bearer {{access_token}}
Accept: application/json


###

GET {{api_url}}/v1/Selection/24 HTTP/1.1
Authorization: Bearer {{access_token}}
Accept: application/json

###




GET {{api_url}}/v1/Selection/28/CriteriaGroups HTTP/1.1
Authorization: Bearer {{access_token}}
Content-Type: application/json
Accept: application/json

###

GET {{api_url}}/v1/List/SelectionCategory/Items HTTP/1.1
Authorization: Bearer {{access_token}}
Content-Type: application/json
Accept: application/json
Accept-Language: en

###

#- beforeTime
GET {{api_url}}/v1/appointment?$select=date,type,text,contact/name?&$filter=date after '2020-05-28T15:00:00' HTTP/1.1
Authorization: Bearer {{access_token}}
Content-Type: application/json
Accept: application/json

###

#- beforeTime
GET {{api_url}}/v1/appointment?$select=date,type,text,contact/name?&$filter=date thisPeriod 1 4 HTTP/1.1
Authorization: Bearer {{access_token}}
Content-Type: application/json
Accept: application/json

###

#***********************************************************************************
# Create Selection
#***********************************************************************************

GET {{api_url}}/v1/Selection/default HTTP/1.1
Authorization: Bearer {{access_token}}
Content-Type: application/json
Accept: application/json

###

#***********************************************************************************
# Save Selection
#***********************************************************************************
POST {{api_url}}/v1/Selection HTTP/1.1
Authorization: Bearer {{access_token}}
Content-Type: application/json
Accept: application/json

{
  "Description": "Testing Selections (Description)",
  "Postit": "",
  "SelectionCategory": {
    "Id": 2,
  },
  "IncludePerson": 0,
  "Name": "Selections from API (Name)",
  "SelectionType": "Dynamic",
  "CompanyUnique": false,
  "TargetTableNumber": 5,
  "TargetTableName": "contact",
  "Completed": false,
  "LeftSelectionId": 0,
  "RightSelectionId": 0,
  "SelectionUnionType": "Unknown",
  "MainProviderName": "ContactPersonDynamicSelectionV2",
  "ShadowProviderName": "",
  "MainHeading": "[SR_SELECTION_DYNAMICSELECTION_OF] [SR_COMPANY_AND_PERSON] (MainHeading)",
  "MemberTabHeading": "[SR_COMPANY_AND_PERSON] (MemberTabeHeading)",
  "VisibleFor": [
    {
      "VisibleId": 0,
      "Visibility": "All",
    }
  ]
}

###

GET {{api_url}}/v1/Selection/28 HTTP/1.1
Authorization: Bearer {{access_token}}
Content-Type: application/json
Accept: application/json

###

POST {{api_url}}/v1/Agents/Archive/GetArchiveListByColumns HTTP/1.1
Authorization: Bearer {{access_token}}
Accept: application/json; charset=utf-8
Content-Type: application/json; charset=utf-8
Accept-Language: en

{
  "ProviderName": "ContactPersonDynamicSelectionV2",
  "Columns": [
    "firstName",
    "lastName"
  ],
  "SortOrder": [
    {
      "Name": "firstName",
      "Direction": "ASC"
    }
  ],
  "Restriction": [
    {
      "Name": "selectionId",
      "Operator": "=",
      "Values": [
        "34"
      ]
    }
  ],
  "Entities": [
    "person"
  ],
  "Page": 0,
  "PageSize": 100
}
###

GET {{api_url}}/v1/archive/ContactPersonDynamicSelectionV2?$select=firstName,lastName&$filter=selectionId = 34 HTTP/1.1
Authorization: Bearer {{access_token}}
Content-Type: application/json
Accept: application/json

###


GET {{api_url}}/v1/archive/contactselection?$select=name,Count(name):Footer&$filter=selectionId eq 145379&$options=GrandTotal=true&$top=50000000 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{access_token}}

###

GET {{api_url}}/v1/selection/145379/members?$select=name HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{access_token}}

###