###

GET {{api_url}}/v1/String/SR_TICKETARCHIVE_STATUS_OPEN HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

###

POST {{api_url}}/v1/Agents/Resource/GetResourceSubstitutions
Authorization: Bearer {{token}}
Accept: application/json; charset=utf-8
Accept-Language: en
Content-Type: application/json; charset=utf-8

{
  "ResourceNames": [
    "SR_TICKETARCHIVE_STATUS_OPEN"
  ],
  "Culture": "en"
}

###

GET {{api_url}}/v1/MDOList/resource?search="SR_TICKETARCHIVE_STATUS_OPEN" HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json
