###
GET {{api_url}}/v1/Ticket/66 HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json; charset=utf-8

###

GET {{api_url}}/v1/Ticket/159 HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json; charset=utf-8
SO-TimeZone: US

###

GET {{api_url}}/v1/Person/15 HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json; charset=utf-8
SO-TimeZone: NO

###
GET {{api_url}}/v1/archive/dynamic?$select=ticket_customers.ticket_id,ticket_customers.ticket_id.(ticket->id).title,ticket_customers.ticket_id.(ticket->id).last_changed,ticket_customers.ticket_id.(ticket->id).created_at&$filter=ticket_customers.customer_id eq 49 HTTP/1.1
Accept: application/json
Authorization: Bearer {{token}}
SO-TimeZone: UTC, includeTZOffset

###
GET {{api_url}}/v1/archive/dynamic?$select=person.person_id,person.registered&$filter=person.person_id eq 49 HTTP/1.1
Accept: application/json
Authorization: Bearer {{token}}
SO-TimeZone: UTC, includeTZOffset


###

POST {{api_url}}/v1/Ticket HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json; charset=utf-8
Content-Type: application/json; charset=utf-8

{
  "TicketId": 0,
  "Title": "Testing Two with Lukasz",
  "CreatedAt": "0001-01-01T00:00:00Z",
  "LastChanged": "0001-01-01T00:00:00Z",
  "ReadByOwner": "0001-01-01T00:00:00Z",
  "ReadByCustomer": "0001-01-01T00:00:00Z",
  "FirstReadByOwner": "0001-01-01T00:00:00Z",
  "FirstReadByUser": "0001-01-01T00:00:00Z",
  "Activate": "0001-01-01T00:00:00Z",
  "ClosedAt": "0001-01-01T00:00:00Z",
  "RepliedAt": "0001-01-01T00:00:00Z",
  "AlertTimeout": "0001-01-01T00:00:00Z",
  "Deadline": "0001-01-01T00:00:00Z",
  "CreatedBy": {
  },
  "Author": null,
  "OwnedBy": {
  },
  "Category": {
    "TicketCategoryId": 3,
    "DefaultTicketStatus": {
      "TicketStatusId": 12
    },
    "DefaultMessageStatus": {
      "TicketStatusId": 2
    }
  },
  "Slevel": "External",
  "Priority": {
  },
  "BaseStatus": "Active",
  "Status": {
  },
  "Origin": "Unknown",
  "Person": null,
  "SecondaryPersons": [],
  "AlertLevel": 0,
  "ConnectId": -1,
  "ReadStatus": "Unknown",
  "TimeToReply": 0,
  "RealTimeToReply": 0,
  "TimeToClose": 0,
  "RealTimeToClose": 0,
  "TimeSpentInternally": 0,
  "TimeSpentExternally": 0,
  "TimeSpentQueue": 0,
  "RealTimeSpentInternally": 0,
  "RealTimeSpentExternally": 0,
  "RealTimeSpentQueue": 0,
  "HasAttachment": false,
  "NumReplies": 0,
  "NumMessages": 0,
  "FromAddress": null,
  "Messages": [],
  "Tags": [],
  "Language": null,
  "Sentiment": 0,
  "SentimentConfidence": 0,
  "SuggestedCategoryId": 0,
  "SuggestedCategoryName": null,
  "OrigHumanCategoryId": 0,
  "IconHint": "svgNav_cs_blue"
}


GET {{api_url}}/v1/TicketMessage/23 HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json; charset=utf-8

###

POST {{api_url}}/v1/TicketMessage HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json; charset=utf-8
Content-Type: application/json; charset=utf-8

{
  "EjMessageId": 23,
  "Ticket": {
    "TicketId": 13,
    "Title": "Test html edit",
    "CreatedAt": "2022-10-17T08:26:00",
    "LastChanged": "2022-10-17T08:26:00",
    "ReadByOwner": "0001-01-01T00:00:00",
    "ReadByCustomer": "0001-01-01T00:00:00",
    "FirstReadByUser": "2022-10-17T08:26:01",
    "Activate": "0001-01-01T00:00:00",
    "ClosedAt": "0001-01-01T00:00:00",
    "RepliedAt": "0001-01-01T00:00:00",
    "AlertTimeout": "0001-01-01T00:00:00",
    "Deadline": "2022-10-17T08:26:00",
    "CreatedBy": 2,
    "CreatedByName": "TY",
    "Author": "TY",
    "OwnedBy": 1,
    "OwnedByName": "",
    "Category": 1,
    "CategoryName": "Support",
    "CategoryFullname": "Support",
    "Slevel": "External",
    "Priority": 2,
    "PriorityName": "Medium",
    "BaseStatus": "Active",
    "TicketStatus": 1,
    "TicketStatusDisplayValue": "Open",
    "Origin": "Internal",
    "CustId": -1,
    "PersonFirstname": "",
    "PersonMiddleName": "",
    "PersonLastname": "",
    "PersonFullname": "",
    "AlertLevel": 1,
    "ConnectId": -1,
    "ReadStatus": "Red",
    "TimeToReply": 0,
    "RealTimeToReply": 0,
    "TimeToClose": 0,
    "RealTimeToClose": 0,
    "TimeSpentInternally": 0,
    "TimeSpentExternally": 0,
    "TimeSpentQueue": 0,
    "RealTimeSpentInternally": 0,
    "RealTimeSpentExternally": 0,
    "RealTimeSpentQueue": 0,
    "HasAttachment": false,
    "NumReplies": 1,
    "NumMessages": 1,
    "FromAddress": "",
    "ContactId": 0,
    "ContactName": "",
    "OwnedByAssociateId": 0,
    "Language": "",
    "Sentiment": 0,
    "SentimentConfidence": 0,
    "TableRight": {
    },
    "FieldProperties": {
    }
  },
  "Author": "TY",
  "Slevel": "External",
  "Type": "Html",
  "MessageId": " ",
  "TimeSpent": 0,
  "Body": "This should be html \r\n\r\n",
  "HtmlBody": "<html>\n<head>\n\t<title></title>\n</head>\n<body style=\"font: normal 11pt 'Verdana'\">\n<p>This should be html</p>\n</body>\n</html>",
  "EmailHeader": "",
  "DebugInfo": "",
  "MailSorter": "",
  "MessageCategory": "Message",
  "Person": null,
  "SearchTitle": "Test html edit",
  "MessageHeaders": [],
  "Important": false,
  "Language": "",
  "Sentiment": 0,
  "SentimentConfidence": 0,
  "ExtraFields": {},
  "CustomFields": {}
}


###

## $select=
## - ticket_customers.ticket_id,
## - ticket_customers.customer_id,
## - ticket_customers.(ticket.id, customer.id)
## - Count(ticket_customers.id)
## - &$filter=ticket_customers.customer_id eq {{person_id}}
@person_id=49

GET {{api_url}}/v1/Archive/dynamic?$select=ticket_customers.ticket_id,ticket.(ticket_customers->ticket_id).title,Count(ticket_customers.id)&$filter=ticket_customers.customer_id eq {{person_id}} HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

###

GET {{api_url}}/v1/Archive/dynamic?$select=ticket.id,ticket.title,Count(ticket.id)&$filter=ticket_customers.customer_id eq {{person_id}} HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

###


GET {{api_url}}/v1/Archive/dynamic?$select=ticket.id,ticket.title,ticket.status,ticket.last_changed,ticket.(ej_message->id).html_body&$filter=ticket.id eq 127 HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

###

GET {{api_url}}/v1/Archive/dynamic?$select=ej_message.id,ej_message.ticket_id,ej_message.html_body,ej_message.ticket_id.id,ej_message.ticket_id.status,ej_message.ticket_id.last_changed&$filter=ej_message.ticket_id eq 127 HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

###

GET {{api_url}}/v1/Archive/dynamic?$select=message_id.id,message_id.message_id,message_id.domain,message_id.item_id&$filter=message_id.item_id in (316,382,383,384,385) HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

###

GET {{api_url}}/v1/Archive/dynamic?$select=ej_message.id,ej_message.ticket_id,ej_message.message_id,ej_message.email_header&$filter=ej_message.message_id isNot '' HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

###

GET {{api_url}}/v1/Archive/dynamic?$select=message_header.id,message_header.message_id,message_header.type,message_header.name,message_header.value,message_header.std_item
Authorization: Bearer {{token}}
Accept: application/json

###

GET {{api_url}}/v1/Archive/dynamic?$select=message_id.id,message_id.message_id,message_id.domain,message_id.item_id HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

###


GET {{api_url}}/v1/Archive/dynamic?$select=s_message.mother_id HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

###