###

POST {{api_url}}/v1/Agents/ViewState/GetCurrent HTTP/1.1
Authorization: Bearer {{access_token}}
Accept: application/json; charset=utf-8
Content-Type: application/json; charset=utf-8

{
    "HistoryName": "SoProtocolPageAndView"
}

###

POST {{api_url}}/v1/Agents/ViewState/GetHistories?$select=HistoryName HTTP/1.1
Authorization: Bearer {{access_token}}
Accept: application/json; charset=utf-8
